### ISSUE TITLE
Reading documentation in GitHub does not show images

### ISSUE THREAD

**Issue by omitar** [oasislabs/docs#65] opened 2019-08-24 09:21 UTC
For example, README.md points to `system_diagram.png`, but it does not really work: https://github.com/oasislabs/docs/blob/master/whats_new/system_diagram.png

On deployed documentation image is correctly available at: https://docs.oasis.dev/whats_new/system_diagram.png

Given that people will find README and try to read it, we should make sure all images are also available for those who directly read documentation in GitHub.

Otherwise make README just a link to documentation website.

**Comment by nhynes** [comment] 2019-08-24 09:23
Duplicate of #57

**Closed by nhynes** 2019-08-24 09:23 UTC
